debug: true

# Logger Config
logging:
    level:
        com:
            ahccc: debug

server:
    port: 9091

spring:
    profiles:
        active: dev
    cloud:
        #sentinel相关配置
        sentinel:
          eager: true
          transport:
            dashboard: 127.0.0.1:9876   #控制台地址
            port: 8719    #提供的监听端口


    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://198.168.31.249:3306/ahccc_demo?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: ahcccrjb
        driver-class-name: com.mysql.cj.jdbc.Driver

        druid:
            # 数据源配置
            max-active: 20
            initial-size: 1
            max-wait: 60000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 20

    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        encoding: utf-8
        mode: HTML5

    cache:
        jcache:
            config: classpath:cache/ehcache.xml

mybatis-plus:
    check-config-location: false
    # MyBatis 配置文件位置，如果您有单独的 MyBatis 配置，请将其路径配置到 configLocation 中，具体配置参考官方文档 http://www.mybatis.org/mybatis-3/zh/configuration.html
    #  config-location: classpath:mybatis/mybatis-config.xml
    # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
    mapper-locations: classpath*:**/*Mapper.xml
    # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
    #  type-aliases-package: com.baomidou.mybatisplus.samples.quickstart.model
    # type-aliases-super-type: java.lang.Object
    # type-handlers-package: com.baomidou.mybatisplus.samples.quickstart.handler
    global-config:
        db-config:
            id-type: auto

    executor-type: simple

    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
